version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'med-ua'
      MYSQL_USER: 'med'
      MYSQL_PASSWORD: 'Medicina'
      MYSQL_ROOT_PASSWORD: 'Palmeras61212'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    build: .
    image: soyseeb/med-auth-server:latest
    container_name: med-auth-server
