version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'med-ua'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'med'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Medicina'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Palmeras61212'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  app:
    build: .
    image: soyseeb/med-auth-server:latest
    container_name: med-auth-server
